CREATE TABLE Passports
(
	PassportID INT PRIMARY KEY IDENTITY(101,1) NOT NULL,
	PassportNumber NVARCHAR(100) NOT NULL
)
CREATE TABLE Persons
(
	PersonID INT PRIMARY KEY IDENTITY NOT NULL,
	FirstName NVARCHAR (50) NOT NULL,
	Salaray DECIMAL(7,2) NOT NULL,
	PassportID INT REFERENCES Passports(PassportID) NOT NULL UNIQUE
)

INSERT INTO Passports (PassportNumber)
VALUES
('N34FG21B'),
('K65LO4R7'),
('ZE657QP2');

INSERT INTO Persons (FirstName, Salaray, PassportID)
VALUES 
('Roberto', 43300.00, 102),
('Tom', 56100.00, 103),
('Yana', 60200.00, 101)